### ISSUE TITLE
MenuBar disappearing 

### ISSUE THREAD

**Issue by HelmoHass** [tbrek/BashBar#11]
I've notice that after using the Sudo command the menu diappear from the Menubar, it does not crashes as its still available from ActivityMonitor, its just no more available after the call.
This is during the execution
![1](https://user-images.githubusercontent.com/33957277/33209803-eed07e4a-d117-11e7-89c4-445f8b8e5d24.png)
And after, no more available from menubar
![2](https://user-images.githubusercontent.com/33957277/33209807-f148883e-d117-11e7-96a4-d1b4db97a20e.png)
after in ActivityMonitor still present
![3](https://user-images.githubusercontent.com/33957277/33209810-f2e37c44-d117-11e7-88fd-cdce43aed1fd.png)

I'm using also Bartender to keep my menus unintrusive, but i don't think it is in any way related to that

**Comment by tbrek** [comment]
Thanks. Does it happend with Bartender turned off? I’ve tried recreating the issue with latest version of Bartender with no luck.

**Comment by HelmoHass** [comment]
Well, i'm out of words now, very strangely now i'm unable to reproduce it too. with or without Bartender, the issue seems gone..

**Comment by tbrek** [comment]
I'll leave it open until the end of the week.

**Comment by HelmoHass** [comment]
I'm now using the 1.2 you recently delivered, and i'd like to make a request concerning the prompt output window. (thanks for that)
could you make it as a panel instead of view only?  As it is, its impossible scroll the output or resize.

**Comment by tbrek** [comment]
Sure. Will make it scrollable.

**Comment by tbrek** [comment]
Output window is now scrollable and resizable.
