### ISSUE TITLE
Add Variables

### ISSUE THREAD

**Issue by warmup72** [tbrek/BashBar#17]
Hi,
ist this project still under work?
I like this bashbar, but I miss a feature.
It would be cool, is there were the posibility to add Variables für "Input"- and "Output"-folder and some extra parameters.
Maybe You can add something like %%in%%, %%out%% and %%param%%.
If you set such variables during execution bashbar will ask for specific variables.

**Comment by tbrek** [comment]
Hey, good idea. I will something like `%var% [desc]` which then could display input dialog also showing var's description.

**Comment by warmup72** [comment]
That sounds great. I spontaneously fall into 5 necessary parameters:
Directory and file input or output and a free text field for additional parameters

If you want to expand it further, you could also add the option for a parameter selection field
So a 
%select -ltr | -la | % [ls parameters] 
would then lead to this at runtime. that there is a selection of the individual parameters before the command is issued.

**Comment by tbrek** [comment]
Hey. Added in the latest release https://github.com/tbrek/BashBar/releases/tag/v.1.8.0, also updated README.

**Comment by warmup72** [comment]
Hi Thank You for this cool and fast feature!
I though it also would be great to have different classes of variable, so that you can choose a variable-type file or folder which leads you to a file/folder-choosing-dialog

**Comment by tbrek** [comment]
> Hi Thank You for this cool and fast feature! I though it also would be great to have different classes of variable, so that you can choose a variable-type file or folder which leads you to a file/folder-choosing-dialog

No worries. I've add two types of variables in 1.8.1. More info in README

**Comment by warmup72** [comment]
Wow amazing fast ... and it works!
Unfortunaly since 1.8 the option for the automatic Resultview ist gone.
In my option it makes sense to have the posibility to activate this for every Command seperat. (Maybe checkbox in the Configview behind every Command)

**Comment by tbrek** [comment]
> Wow amazing fast ... and it works!
> Unfortunaly since 1.8 the option for the automatic Resultview ist gone.
> In my option it makes sense to have the posibility to activate this for every Command seperat. (Maybe checkbox in the Configview behind every Command)

Added global option in 1.8.1 to show them for time being as separate one requires more work.
